// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mystore.Models;

#nullable disable

namespace mystore.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    partial class EmployeeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mystore.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<int>("FormAge")
                        .HasColumnType("int")
                        .HasColumnName("FormAge");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FormName");

                    b.Property<string>("FormTextArea")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("FormTextArea");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("FormGender");

                    b.Property<string>("Married")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MarriedStatus");

                    b.HasKey("ID");

                    b.ToTable("employees1");
                });
#pragma warning restore 612, 618
        }
    }
}
